package HelloApp;


/**
* HelloApp/HelloOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloApp.IDL
* 28 Nisan 2020 Salý 14:20:36 EET
*/

public interface HelloOperations 
{
  String hellomessage ();
  void hellomessage (String newHellomessage);
} // interface HelloOperations
